"""Generate screenshots/README.md from screenshots/screenshots.json."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
entries = sorted(json.loads((ROOT / "screenshots/screenshots.json").read_text()), key=lambda e: e["filename"])
lines = [
    "# Screenshot inventory",
    "",
    "Every screenshot is a real terminal session. `scripts/term_record.py` runs the commands in a real",
    "interactive bash inside a pseudo-terminal and records every byte (the recording is refused if a",
    "secret pattern or the literal API key appears). `tools/screenshot/render.mjs` replays those exact",
    "bytes in xterm.js (a real terminal emulator) in headless Chrome and captures the window. Nothing is",
    "retyped or edited. The raw byte recordings are in `screenshots/recordings/*.cast` (asciinema v2",
    "format, so `asciinema play` can replay them). Mid-run frames are cut from the same recording at the",
    "moment the quoted text first appeared.",
    "",
    "Direct desktop capture was not used because GNOME on Wayland refuses programmatic window screenshots.",
    "",
    "| File | What it shows | Commands | Recorded (UTC) | Source artifact | Blog section / caption |",
    "|---|---|---|---|---|---|",
]
for e in entries:
    cmds = "<br>".join(f"`{c}`" for c in e["commands"]).replace("|", "\\|")
    lines.append(
        f"| `{e['filename']}` | {e['caption']} ({e['frame']}) | {cmds} | {e['recorded_utc'][:19]} | "
        f"`{e['source_artifact']}` | {e['blog_section']} |"
    )
lines += [
    "",
    "Figures in `results/figures/` are generated by `scripts/make_figures.py` from result tables.",
    "",
]
(ROOT / "screenshots/README.md").write_text("\n".join(lines))
print(f"{len(entries)} screenshots indexed")
