"""Build blog/claim_provenance.json and VERIFY every quantitative blog claim against the artifacts.

Each claim: the text as it appears in the blog, the source artifact, the calculation (a Python
expression over the loaded artifacts), the value shown in the blog, and a tolerance. The script
recomputes each value and fails (exit 1) if any shown value disagrees with the artifact, or if the
shown text is missing from the blog.
"""

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
M = json.loads((ROOT / "results/analysis/metrics.json").read_text())
S = json.loads((ROOT / "results/analysis/scale_metrics.json").read_text())
T = {p.stem: pd.read_csv(p) for p in (ROOT / "results/tables").glob("*.csv")}
BLOG = (ROOT / "blog/jev-security-prioritization.md").read_text()
F = json.loads((ROOT / "results/analysis/frontier_metrics.json").read_text())
FM = F["models"]
MJ, SJ, FJ = (
    "results/analysis/metrics.json",
    "results/analysis/scale_metrics.json",
    "results/analysis/frontier_metrics.json",
)
U = S["agreement_uniform_sample"]["all"]["urgency"]


def cf(dom, attr, col):
    t = T["counterfactual_attribute_effects"]
    return float(t[(t.domain == dom) & (t.attribute == attr)][col].iloc[0])


def ms(dom, field, mode, col):
    t = T["missing_summary"]
    return float(t[(t.domain == dom) & (t.field == field) & (t["mode"] == mode)][col].iloc[0])


P = M["primary"]
# (blog text, artifact, calculation, fields, shown value, tolerance)
CLAIMS = [
    ("879 API calls", MJ, "M['run']['requests_total_incl_smoke']", "run.requests_total_incl_smoke", 879, 0),
    ("1,084 cases needed 878 API calls", MJ, "M['run']['cases_total']", "run.cases_total", 1084, 0),
    (
        "All 879 benchmark requests came back",
        MJ,
        "M['run']['model_snapshots']['typesafe/jev-1.13-20260917']",
        "run.model_snapshots",
        879,
        0,
    ),
    (
        "Jev chose DEFER with probability 0.71",
        "results/raw/smoke/responses/",
        "json.loads(next((ROOT/'results/raw/smoke/responses').glob('*.json')).read_text())['response_body']['answers']['disposition']['probabilities']['DEFER']",
        "answers.disposition.probabilities.DEFER",
        0.71,
        0,
    ),
    (
        "1,215 input tokens cost $0.00005103",
        "results/raw/smoke/responses/",
        "json.loads(next((ROOT/'results/raw/smoke/responses').glob('*.json')).read_text())['response_body']['usage']['input_tokens']",
        "usage.input_tokens",
        1215,
        0,
    ),
    (
        "**55%** (95% CI 46 to 64%)",
        MJ,
        "P['sca']['jev']['disposition']['accuracy']",
        "primary.sca.jev.disposition.accuracy",
        0.55,
        0.005,
    ),
    (
        "**55%** (95% CI 46 to 64%)",
        MJ,
        "P['sca']['jev']['disposition']['accuracy_ci95'][0]",
        "accuracy_ci95[0]",
        0.46,
        0.005,
    ),
    (
        "**55%** (95% CI 46 to 64%)",
        MJ,
        "P['sca']['jev']['disposition']['accuracy_ci95'][1]",
        "accuracy_ci95[1]",
        0.64,
        0.005,
    ),
    (
        "| 25% | 53% |",
        MJ,
        "P['sca']['b0_severity_only']['disposition']['accuracy']",
        "primary.sca.b0",
        0.25,
        0.005,
    ),
    (
        "| 25% | 53% |",
        MJ,
        "P['sca']['b1_context_points']['disposition']['accuracy']",
        "primary.sca.b1",
        0.53,
        0.005,
    ),
    (
        "| 98% | 67% | 93% |",
        MJ,
        "P['sca']['jev']['urgency']['recall@0.5']",
        "primary.sca.jev.urgency.recall@0.5",
        0.98,
        0.005,
    ),
    ("| 68% | 43% | 68% |", MJ, "P['sca']['jev']['urgency']['precision@0.5']", "precision@0.5", 0.68, 0.005),
    (
        "| 0.63 | 1.40 | 0.61 |",
        MJ,
        "P['sca']['jev']['score']['mae']",
        "primary.sca.jev.score.mae",
        0.63,
        0.005,
    ),
    (
        "| 0.97 (0.94 to 0.99)",
        MJ,
        "P['sca']['jev']['urgency']['auc']",
        "primary.sca.jev.urgency.auc",
        0.97,
        0.005,
    ),
    (
        "McNemar p = 5.4e-6",
        MJ,
        "P['sca']['mcnemar_jev_vs_b0']['jev_right_baseline_wrong']",
        "mcnemar_jev_vs_b0",
        45,
        0,
    ),
    (
        "McNemar p = 5.4e-6",
        MJ,
        "float(P['sca']['mcnemar_jev_vs_b0']['p_value_sci'])",
        "p_value_sci",
        5.4e-6,
        0.05e-6,
    ),
    (
        "26 vs 23, p = 0.78",
        MJ,
        "P['sca']['mcnemar_jev_vs_b1']['p_value']",
        "mcnemar_jev_vs_b1.p_value",
        0.78,
        0.005,
    ),
    (
        "**49%** (95% CI 40 to 58%)",
        MJ,
        "P['sast']['jev']['disposition']['accuracy']",
        "primary.sast.jev.disposition.accuracy",
        0.49,
        0.005,
    ),
    (
        "| 21% | 38% |",
        MJ,
        "P['sast']['b1_context_points']['disposition']['accuracy']",
        "primary.sast.b1",
        0.38,
        0.005,
    ),
    ("| 87% | 59% | 100% |", MJ, "P['sast']['jev']['urgency']['recall@0.5']", "recall@0.5", 0.87, 0.005),
    (
        "| 80% | 36% | 52% |",
        MJ,
        "P['sast']['b1_context_points']['urgency']['precision']",
        "b1 precision",
        0.52,
        0.005,
    ),
    ("| 0.56 | 1.63 | 0.92 |", MJ, "P['sast']['jev']['score']['mae']", "score.mae", 0.56, 0.005),
    (
        "| 0.93 (0.88 to 0.97) | n/a | 0.91 |",
        MJ,
        "P['sast']['jev']['urgency']['auc']",
        "urgency.auc",
        0.93,
        0.005,
    ),
    (
        "40 vs 9, p = 9.3e-6",
        MJ,
        "float(P['sast']['mcnemar_jev_vs_b0']['p_value_sci'])",
        "p_value_sci",
        9.3e-6,
        0.05e-6,
    ),
    ("36 vs 23, p = 0.12", MJ, "P['sast']['mcnemar_jev_vs_b1']['p_value']", "p_value", 0.12, 0.005),
    (
        "false escalation 60%",
        MJ,
        "P['sast']['b1_context_points']['disposition']['false_escalation_rate']",
        "false_escalation_rate",
        0.60,
        0.005,
    ),
    (
        "Jev rarely does (5%)",
        MJ,
        "P['sast']['jev']['disposition']['false_escalation_rate']",
        "false_escalation_rate",
        0.05,
        0.005,
    ),
    (
        "(18 of 42 in\nSCA, 29 of 45 in SAST)",
        "results/tables/confusion_sca_jev.csv",
        "int(T['confusion_sca_jev'].set_index('reference').loc['STANDARD','DEFER'])",
        "STANDARD->DEFER",
        18,
        0,
    ),
    (
        "(18 of 42 in\nSCA, 29 of 45 in SAST)",
        "results/tables/confusion_sast_jev.csv",
        "int(T['confusion_sast_jev'].set_index('reference').loc['STANDARD','DEFER'])",
        "STANDARD->DEFER",
        29,
        0,
    ),
    (
        "mostly said ACCELERATED (14 of 24)",
        "results/tables/confusion_sast_jev.csv",
        "int(T['confusion_sast_jev'].set_index('reference').loc['EMERGENCY','ACCELERATED'])",
        "EMERGENCY->ACCELERATED",
        14,
        0,
    ),
    (
        "51 times out of 57",
        MJ,
        "M['disagreement_direction']['sast']['jev_lower_priority']",
        "disagreement_direction.sast",
        51,
        0,
    ),
    (
        "27 lower and 20 higher",
        MJ,
        "M['disagreement_direction']['sca']['jev_higher_priority']",
        "disagreement_direction.sca",
        20,
        0,
    ),
    (
        "raised P(urgent) by 0.28 on average in SCA",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sca','reachable','mean_d_noul')",
        "mean_d_noul",
        0.28,
        0.005,
    ),
    (
        "and 0.29 in SAST",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sast','reachable','mean_d_noul')",
        "mean_d_noul",
        0.29,
        0.005,
    ),
    (
        "14\n  of 15 SCA pairs and 11 of 15 SAST pairs",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sca','reachable','choice_flip_rate')*15",
        "choice_flip_rate",
        14,
        0.01,
    ),
    (
        "14\n  of 15 SCA pairs and 11 of 15 SAST pairs",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sast','reachable','choice_flip_rate')*15",
        "choice_flip_rate",
        11,
        0.01,
    ),
    (
        "+0.28 P(urgent), with 67% of dispositions",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sast','sanitization','choice_flip_rate')",
        "choice_flip_rate",
        0.67,
        0.005,
    ),
    (
        "mean ΔP(urgent) = -0.003, 1 flip in 15",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sast','auth','mean_d_noul')",
        "mean_d_noul",
        -0.003,
        0.0005,
    ),
    (
        "CVSS 5.3 to 9.8 raised P(urgent) by 0.08",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sca','cvss','mean_d_noul')",
        "mean_d_noul",
        0.08,
        0.005,
    ),
    (
        "flipped\n  **zero** SCA dispositions",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sca','cvss','choice_flip_rate')",
        "choice_flip_rate",
        0,
        0,
    ),
    (
        "raised it by 0.12 and flipped 1 of 15",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sast','severity','mean_d_noul')",
        "mean_d_noul",
        0.12,
        0.005,
    ),
    (
        "KEV listing (+0.09 P(urgent), score +0.15",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sca','kev','mean_d_noul')",
        "mean_d_noul",
        0.09,
        0.005,
    ),
    (
        "versus a rubric change of +0.60",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sca','kev','rubric_mean_d_exposure')",
        "rubric_mean_d_exposure",
        0.60,
        0.005,
    ),
    (
        "(score\n  +0.21 versus rubric +1.53)",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sast','attacker_controlled','rubric_mean_d_exposure')",
        "rubric_mean_d_exposure",
        1.53,
        0.005,
    ),
    (
        "(Spearman 0.77 for SCA\nand 0.74 for SAST",
        MJ,
        "M['counterfactual_rank_agreement']['sca']['spearman_jev_d_score_vs_rubric_d_exposure']",
        "spearman",
        0.77,
        0.005,
    ),
    (
        "in 14 of 15 pairs for SAST scanner severity",
        "results/tables/counterfactual_attribute_effects.csv",
        "cf('sast','severity','share_d_noul_positive')*15",
        "share_d_noul_positive",
        14,
        0.01,
    ),
    (
        "B0 got 0 of 24",
        "results/tables/contradiction_cases.csv",
        "int((T['contradiction_cases'].b0_disp == T['contradiction_cases'].ref_disp).sum())",
        "b0 vs ref",
        0,
        0,
    ),
    (
        "toward the context in **all 24 cases**",
        "results/tables/contradiction_cases.csv",
        "int(T['contradiction_cases'].moved_toward_context.sum())",
        "moved_toward_context",
        24,
        0,
    ),
    (
        "mean P(urgent) of\n  0.16 in SCA and 0.20 in SAST",
        MJ,
        "M['contradiction']['sca/high_severity_low_context']['mean_noul']",
        "mean_noul",
        0.16,
        0.005,
    ),
    (
        "Jev chose REVIEW 50% of the time",
        MJ,
        "M['missing']['overall']['unknown_vs_omitted']['unknown']['selected_review']",
        "selected_review",
        0.50,
        0.005,
    ),
    (
        "put 0.34 more\n  probability on REVIEW",
        MJ,
        "M['missing']['overall']['unknown_vs_omitted']['unknown']['d_p_review']",
        "d_p_review",
        0.34,
        0.005,
    ),
    (
        "Jev chose REVIEW 1 time out of 80",
        MJ,
        "M['missing']['overall']['unknown_vs_omitted']['omitted']['selected_review']*80",
        "selected_review",
        1,
        0.01,
    ),
    (
        "(+0.002)",
        MJ,
        "M['missing']['overall']['unknown_vs_omitted']['omitted']['d_p_review']",
        "d_p_review",
        0.002,
        0.0005,
    ),
    (
        "Unknown reachability sent\n  every single case to REVIEW",
        "results/tables/missing_summary.csv",
        "ms('sast','reachable','unknown','selected_review') + ms('sca','reachable','unknown','selected_review')",
        "selected_review",
        2.0,
        0,
    ),
    (
        "Jev picked\nREVIEW on 32%",
        MJ,
        "M['missing']['overall']['jev_selected_review_when_ref_review']",
        "jev_selected_review_when_ref_review",
        0.32,
        0.005,
    ),
    (
        "(5 of 16)",
        MJ,
        "M['missing']['overall']['jev_review_recall_urgency_stakes']*M['missing']['overall']['n_urgency_stakes']",
        "review recall urgency stakes",
        5,
        0.01,
    ),
    (
        "raised P(REVIEW) to 0.28 and 0.25",
        MJ,
        "M['inconsistent']['sca']['mean_p_review']",
        "mean_p_review",
        0.28,
        0.005,
    ),
    (
        "only 3 times in 20",
        MJ,
        "M['inconsistent']['sca']['review_selected_rate']*10 + M['inconsistent']['sast']['review_selected_rate']*10",
        "review_selected_rate",
        3,
        0.01,
    ),
    (
        "Mean ΔP(urgent) was +0.02 for",
        MJ,
        "M['adversarial']['by_variant']['inj_down']['d_noul']",
        "d_noul",
        0.02,
        0.005,
    ),
    (
        '+0.005 for "classify as EMERGENCY"',
        MJ,
        "M['adversarial']['by_variant']['inj_up']['d_noul']",
        "d_noul",
        0.005,
        0.0005,
    ),
    (
        "largest single shift from either was 0.11",
        "results/tables/adversarial_pairs.csv",
        "float(T['adversarial_pairs'][T['adversarial_pairs'].variant.str.startswith('inj')].d_noul.abs().max())",
        "d_noul",
        0.11,
        0,
    ),
    (
        "disposition in 17 of 20",
        "results/tables/adversarial_pairs.csv",
        "int(T['adversarial_pairs'][T['adversarial_pairs'].variant=='argue_down'].flip.sum())",
        "flip",
        17,
        0,
    ),
    (
        "In 16 of the 17 flips Jev went to **REVIEW**",
        "results/tables/adversarial_pairs.csv",
        "int(((T['adversarial_pairs'].variant=='argue_down') & T['adversarial_pairs'].flip & (T['adversarial_pairs'].choice_adv=='REVIEW')).sum())",
        "choice_adv",
        16,
        0,
    ),
    (
        "lowered P(urgent) by 0.24 on average, and by up to 0.41",
        MJ,
        "M['adversarial']['by_variant']['argue_down']['d_noul']",
        "d_noul",
        -0.24,
        0.005,
    ),
    (
        "Brier score was 0.13 and\n  0.12, against 0.24",
        MJ,
        "P['sca']['jev']['urgency']['brier']",
        "brier",
        0.13,
        0.005,
    ),
    (
        "ECE was 0.20 in SCA and 0.14 in SAST",
        MJ,
        "P['sca']['jev']['urgency']['ece_10bin']",
        "ece_10bin",
        0.20,
        0.005,
    ),
    (
        "ECE was 0.20 in SCA and 0.14 in SAST",
        MJ,
        "P['sast']['jev']['urgency']['ece_10bin']",
        "ece_10bin",
        0.14,
        0.005,
    ),
    (
        "urgent by the rubric only 2 times out of 11",
        MJ,
        "[b for b in P['sca']['jev']['urgency']['reliability'] if b['bin']=='0.6-0.7'][0]['observed']*11",
        "reliability[0.6-0.7]",
        2,
        0.01,
    ),
    (
        "non-urgent SCA cases was\n  0.39",
        MJ,
        "P['sca']['jev']['urgency']['mean_p_not_urgent']",
        "mean_p_not_urgent",
        0.39,
        0.005,
    ),
    (
        "averaged probability 0.66\n  while matching the rubric 52%",
        MJ,
        "P['all']['jev_choice_selected_prob_vs_correct']['mean_selected_prob']",
        "mean_selected_prob",
        0.66,
        0.005,
    ),
    (
        "(ECE 0.15)",
        MJ,
        "P['all']['jev_choice_selected_prob_vs_correct']['ece_10bin']",
        "ece_10bin",
        0.15,
        0.005,
    ),
    (
        "kept 80%, and turning the whole state\ninto a prose paragraph kept 85%",
        "results/tables/paraphrase_summary.csv",
        "float(T['paraphrase_summary'][T['paraphrase_summary'].variant=='prose'].agreement.mean())",
        "agreement",
        0.85,
        0.005,
    ),
    (
        "same\ndisposition in 19 of 20 groups",
        MJ,
        "M['repeat']['groups_with_identical_choice']",
        "groups_with_identical_choice",
        19,
        0,
    ),
    ("varying by at most 0.05", MJ, "M['repeat']['max_noul_range']", "max_noul_range", 0.05, 0),
    ("| Input tokens | 1,087,741", MJ, "M['run']['input_tokens_total']", "input_tokens_total", 1087741, 0),
    ("| Total cost | **$0.0457** |", MJ, "M['run']['cost_total_usd']", "cost_total_usd", 0.0457, 0.00005),
    (
        "| Cost per 1,000 decisions | $0.052 |",
        MJ,
        "M['run']['cost_per_1000_requests_usd']",
        "cost_per_1000_requests_usd",
        0.052,
        0.0005,
    ),
    (
        "median 192 ms, p90 280 ms, p99 471 ms, max 1.87 s",
        MJ,
        "M['run']['latency_ms']['p50']",
        "latency_ms.p50",
        192,
        0.6,
    ),
    (
        "median 192 ms, p90 280 ms, p99 471 ms, max 1.87 s",
        MJ,
        "M['run']['latency_ms']['p99']",
        "latency_ms.p99",
        471,
        0.6,
    ),
    (
        "$0.042 per million input tokens",
        MJ,
        "M['run']['usd_per_million_input_tokens_observed']",
        "usd_per_million_input_tokens_observed",
        0.042,
        0.0005,
    ),
    (
        "p ≈ 1e-10 pooled",
        MJ,
        "float(P['all']['mcnemar_jev_vs_b0']['p_value_sci'])",
        "p_value_sci",
        1e-10,
        0.05e-10,
    ),
    (
        "95% of Score answers were within one level",
        MJ,
        "P['all']['jev']['score']['within_1']",
        "within_1",
        0.95,
        0.005,
    ),
]

CLAIMS += [
    ("49,998 of 50,000", SJ, "S['n_ok']", "n_ok", 49998, 0),
    (
        "2 failed on HTTP 520; 1 HTTP 503 succeeded on its retry",
        SJ,
        "S['errors_by_status']['520']",
        "errors_by_status",
        2,
        0,
    ),
    (
        "**21.4 minutes** for the main session, 38.4 decisions per second",
        SJ,
        "S['main_session']['wall_minutes']",
        "main_session.wall_minutes",
        21.4,
        0.05,
    ),
    (
        "**21.4 minutes** for the main session, 38.4 decisions per second",
        SJ,
        "S['main_session']['requests_per_second']",
        "requests_per_second",
        38.4,
        0.05,
    ),
    ("| Input tokens | 62,025,468 |", SJ, "S['input_tokens_total']", "input_tokens_total", 62025468, 0),
    ("| Total cost | **$2.61**", SJ, "S['cost_total_usd']", "cost_total_usd", 2.61, 0.005),
    ("median 194 ms, p99 436 ms", SJ, "S['latency_ms']['p50']", "latency_ms.p50", 194, 0.5),
    ("median 194 ms, p99 436 ms", SJ, "S['latency_ms']['p99']", "latency_ms.p99", 436, 0.5),
    (
        "`typesafe/jev-1.13-20260917` for all 49,998",
        SJ,
        "S['model_snapshots']['typesafe/jev-1.13-20260917']",
        "model_snapshots",
        49998,
        0,
    ),
    (
        "4.5% of findings urgent by the rubric (2,248 of 49,998)",
        SJ,
        "U['n_urgent']",
        "urgency.n_urgent",
        2248,
        0,
    ),
    ("excellent (AUC 0.97)", SJ, "U['auc']", "urgency.auc", 0.97, 0.005),
    (
        "flagged about 7,300 findings",
        SJ,
        "U['recall@0.5'] * U['n_urgent'] / U['precision@0.5']",
        "recall, precision, n_urgent",
        7300,
        50,
    ),
    ("to catch 2,085 of the", SJ, "U['recall@0.5'] * U['n_urgent']", "recall@0.5 * n_urgent", 2085, 0.5),
    ("recall 93%, precision only 29%", SJ, "U['precision@0.5']", "precision@0.5", 0.29, 0.005),
    (
        "The Brier score, 0.090, was *worse* than simply\npredicting the base rate (0.043)",
        SJ,
        "U['brier']",
        "brier",
        0.090,
        0.0005,
    ),
    (
        "The Brier score, 0.090, was *worse* than simply\npredicting the base rate (0.043)",
        SJ,
        "U['brier_base_rate']",
        "brier_base_rate",
        0.043,
        0.0005,
    ),
    ("ECE on the 50k sample was 0.22", SJ, "U['ece_10bin']", "ece_10bin", 0.22, 0.005),
    ("| Jev 1.13 | **186 ms**", FJ, "FM['typesafe/jev-1.13']['latency_ms_p50']", "latency_ms_p50", 186, 0.5),
    (
        "| GPT-6 Sol | 2.53 s | 13.6x slower | $0.0034 | $170 |",
        FJ,
        "FM['openai/gpt-6-sol']['latency_ms_p50']",
        "latency_ms_p50",
        2530,
        5,
    ),
    (
        "| GPT-6 Sol | 2.53 s | 13.6x slower | $0.0034 | $170 |",
        FJ,
        "FM['openai/gpt-6-sol']['latency_ratio_vs_jev_p50']",
        "latency_ratio_vs_jev_p50",
        13.6,
        0.05,
    ),
    (
        "| GPT-6 Sol | 2.53 s | 13.6x slower | $0.0034 | $170 |",
        FJ,
        "FM['openai/gpt-6-sol']['projected_cost_50k_usd']",
        "projected_cost_50k_usd",
        170,
        0.5,
    ),
    (
        "| Claude Sonnet 5 | 2.59 s | 14.0x slower | $0.0043 | $215 |",
        FJ,
        "FM['anthropic/claude-sonnet-5']['latency_ratio_vs_jev_p50']",
        "latency_ratio_vs_jev_p50",
        14.0,
        0.05,
    ),
    (
        "| Claude Sonnet 5 | 2.59 s | 14.0x slower | $0.0043 | $215 |",
        FJ,
        "FM['anthropic/claude-sonnet-5']['projected_cost_50k_usd']",
        "projected_cost_50k_usd",
        215,
        0.5,
    ),
    (
        "| Gemini 3.8 Flash | 5.58 s | 30.1x slower | $0.0013 | $65 |",
        FJ,
        "FM['google/gemini-3.8-flash']['latency_ratio_vs_jev_p50']",
        "latency_ratio_vs_jev_p50",
        30.1,
        0.05,
    ),
    (
        "| Gemini 3.8 Flash | 5.58 s | 30.1x slower | $0.0013 | $65 |",
        FJ,
        "FM['google/gemini-3.8-flash']['projected_cost_50k_usd']",
        "projected_cost_50k_usd",
        65,
        0.5,
    ),
    (
        "| Jev 1.13 | **186 ms** | 1x | **$0.000052** | $2.60 |",
        FJ,
        "FM['typesafe/jev-1.13']['projected_cost_50k_usd']",
        "projected_cost_50k_usd",
        2.60,
        0.005,
    ),
    (
        "All 160 answers were valid JSON",
        FJ,
        "sum(m['valid_answers'] for m in FM.values())",
        "valid_answers",
        160,
        0,
    ),
    (
        "took Jev 9.6 seconds in total and the frontier models 102 to 247 seconds",
        FJ,
        "FM['typesafe/jev-1.13']['sequential_run_time_s_40_cases']",
        "sequential_run_time_s_40_cases",
        9.6,
        0.05,
    ),
    (
        "took Jev 9.6 seconds in total and the frontier models 102 to 247 seconds",
        FJ,
        "FM['google/gemini-3.8-flash']['sequential_run_time_s_40_cases']",
        "sequential_run_time_s_40_cases",
        247,
        0.5,
    ),
    (
        "Claude Sonnet\n5 agreed with my rubric on 78% of dispositions, against 55% for Jev, 55% for Gemini, and 48% for\nGPT-6 Sol",
        FJ,
        "FM['anthropic/claude-sonnet-5']['agreement_descriptive_small_n']['disposition_acc']",
        "disposition_acc",
        0.78,
        0.005,
    ),
    (
        "Claude Sonnet\n5 agreed with my rubric on 78% of dispositions, against 55% for Jev, 55% for Gemini, and 48% for\nGPT-6 Sol",
        FJ,
        "FM['typesafe/jev-1.13']['agreement_descriptive_small_n']['disposition_acc']",
        "disposition_acc",
        0.55,
        0.005,
    ),
    (
        "Claude Sonnet\n5 agreed with my rubric on 78% of dispositions, against 55% for Jev, 55% for Gemini, and 48% for\nGPT-6 Sol",
        FJ,
        "FM['openai/gpt-6-sol']['agreement_descriptive_small_n']['disposition_acc']",
        "disposition_acc",
        0.475,
        0.0051,
    ),
    (
        "cost 83 times\nas much",
        FJ,
        "FM['anthropic/claude-sonnet-5']['cost_per_decision_usd'] / FM['typesafe/jev-1.13']['cost_per_decision_usd']",
        "cost_per_decision_usd ratio",
        83,
        0.5,
    ),
    (
        "(AUC 0.92 to 0.97)",
        FJ,
        "min(m['agreement_descriptive_small_n']['urgency_auc'] for m in FM.values())",
        "urgency_auc",
        0.92,
        0.005,
    ),
]

out, bad = [], 0
for text, art, calc, fields, shown, tol in CLAIMS:
    val = eval(calc)  # noqa: S307 - expressions are defined in this file
    ok = abs(float(val) - float(shown)) <= tol + 1e-9
    in_blog = text in BLOG
    bad += (not ok) or (not in_blog)
    out.append(
        {
            "claim": text.replace("\n", " "),
            "source_artifact": art,
            "calculation": calc,
            "relevant_fields": fields,
            "value_in_blog": shown,
            "recomputed_value": val,
            "matches": ok,
            "text_found_in_blog": in_blog,
        }
    )
    if not ok or not in_blog:
        print(f"MISMATCH: {text!r}: shown={shown} recomputed={val} in_blog={in_blog}")
(ROOT / "blog/claim_provenance.json").write_text(
    json.dumps(
        {
            "generated_by": "scripts/build_claim_provenance.py",
            "n_claims": len(out),
            "all_verified": bad == 0,
            "claims": out,
        },
        indent=1,
        default=str,
    )
    + "\n"
)
print(f"{len(out)} claims checked, {bad} problems")
sys.exit(1 if bad else 0)
